name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 2048
          temp-reserve-mb: 2048
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk libltdl-dev
          pip3 install --user --upgrade virtualenv "buildozer==1.5.0" "Cython<3.0" setuptools wheel --break-system-packages

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          sudo chown -R $USER:$USER .
          # Curățăm doar folderele de build, nu ștergem NDK-ul descărcat
          rm -rf .buildozer/android/platform/build-*
          buildozer --verbose android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
