name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Extreme Disk Cleanup
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf /usr/lib/jvm
          sudo docker image prune -a -f
          sudo apt-get clean
          df -h # Afișează spațiul liber în log pentru verificare

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk libltdl-dev
          pip3 install --user --upgrade virtualenv "buildozer==1.5.0" "Cython<3.0" setuptools wheel --break-system-packages

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          sudo chown -R $USER:$USER .
          # Ștergem folderele de build vechi care ocupă spațiu, dar păstrăm SDK/NDK
          rm -rf .buildozer/android/platform/build-* buildozer --verbose android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
