name: Build APK
on: push
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip build-essential git autoconf automake libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev openjdk-17-jdk libltdl-dev
          pip3 install --user --upgrade "Cython<3.0" virtualenv "buildozer==1.5.0" --break-system-packages

      - name: Build APK
        run: |
          export PATH=$PATH:~/.local/bin
          sudo chown -R $USER:$USER .
          # Curățăm tot ce ține de arhitecturi vechi
          rm -rf .buildozer
          # Forțăm build-ul pentru arhitectura de telefon
          buildozer android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
